### ISSUE TITLE
DemoProject is unavailable

### ISSUE THREAD

**Issue by 1405100494** [Theuntextured/AsyncConveyorPlugin#10]
Hi！
DemoProject is not built with a new version of the plug-in.
The project you uploaded appears to have been built with an older version of the plugin, which is not called that. The blueprints in the project are corrupted.

The log：

The following modules are missing or built with a different engine version:
ConveyorPlugin
ConveyorSystemPlugin
Would you like to rebuild them now?

Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp] [Line: 2616] 
Failed to create Intermediate directory 'C:/Users/D/AppData/Local/UnrealEngine/5.3/Intermediate/'.

0x00007ff73731ac3b UnrealEditor.exe!UnknownFunction []
0x00007ff73730cf90 UnrealEditor.exe!UnknownFunction []
0x00007ff73730d37a UnrealEditor.exe!UnknownFunction []
0x00007ff737310854 UnrealEditor.exe!UnknownFunction []
0x00007ff737326984 UnrealEditor.exe!UnknownFunction []
0x00007ff737329d7a UnrealEditor.exe!UnknownFunction []
0x00007ff9d3957614 KERNEL32.DLL!UnknownFunction []

**Comment by Theuntextured** [comment]
A new version is there.
