### ISSUE TITLE
add some example projects

### ISSUE THREAD

**Issue by 1405100494** [Theuntextured/AsyncConveyorPlugin#8]
Hello, I just bought this plug-in, the plugin content seems to be empty, can you add some example projects?

**Comment by 1405100494** [comment]
I was new to blueprints and had no idea how to reproduce what the example project showed.

**Comment by Theuntextured** [comment]
Unfortunately, adding example projects with the blueprint is not something that I can do because it would make the plugin size very large for no reason. If you want to learn about blueprints, I suggest you look at some of [Ryan Laley's videos](https://www.youtube.com/@RyanLaley). They are very good at teaching you the basics of blueprints!

Also check out the [wili](https://github.com/Theuntextured/AsyncConveyorPlugin/wiki) for a full documentation about how to use the plugin!

Let me know if you have any more doubts!

**Comment by 1405100494** [comment]
> 不幸的是，使用蓝图添加示例项目不是我能做的事情，因为它会无缘无故地使插件大小变得非常大。如果你想了解蓝图，我建议你看一些[Ryan Laley的视频](https://www.youtube.com/@RyanLaley)。他们非常擅长教你蓝图的基础知识！
> 
> 另请查看 [wiki](https://github.com/Theuntextured/AsyncConveyorPlugin/wiki) 以获取有关如何使用该插件的完整文档！
> 
> 如果您还有任何疑问，请告诉我！
There is no example of the main function in the document, most of it is the node introduction, whether you can upload the project file of the sample project in github, the packaged file can not tell people how to use. Most of the plugins and blueprints I've purchased have sample projects or videos that show you how to use the integration. This document is missing the most core node loss example, after reading I do not know how to change the use of those asynchronous nodes.

**Comment by 1405100494** [comment]
> Unfortunately, adding example projects with the blueprint is not something that I can do because it would make the plugin size very large for no reason. If you want to learn about blueprints, I suggest you look at some of [Ryan Laley's videos](https://www.youtube.com/@RyanLaley). They are very good at teaching you the basics of blueprints!
> 
> Also check out the [wiki](https://github.com/Theuntextured/AsyncConveyorPlugin/wiki) for a full documentation about how to use the plugin!
> 
> Let me know if you have any more doubts!

There is no example of the main function in the document, most of it is the node introduction, whether you can upload the project file of the sample project in github, the packaged file can not tell people how to use. Most of the plugins and blueprints I've purchased have sample projects or videos that show you how to use the integration. This document is missing the most core node loss example, after reading I do not know how to change the use of those asynchronous nodes.
