### ISSUE TITLE
Video tutorials and sample projects

### ISSUE THREAD

**Issue by 1405100494** [Theuntextured/AsyncConveyorPlugin#9]
Hi!
I would love to have a video tutorial to show you how to integrate this plug-in into your project. To be honest, I have read the documentation many times, and it does not tell you how to get the goods moving on the conveyor belt, the asynchronous functions only have a brief introduction. I myself implemented a similar process with pure blueprints, detecting collisions to animate objects from end to end along the spline and stopping when blocked. But I can't understand this document.
There is also hope that a sample project can be published on github, the packaged project demo is completely impossible for me to understand how to implement these features with plug-ins. In fact, many authors put the examples directly in the plug-in directory, although it does make the file larger. If you want to keep it simple, please upload it on github. This is very important for beginners.
Thanks!

**Comment by Theuntextured** [comment]
Alright. I will post it in a bit.

**Comment by Theuntextured** [comment]
Done. It is in https://github.com/Theuntextured/AsyncConveyorPlugin/releases/tag/v1.2.0

**Comment by 1405100494** [comment]
The following modules are missing or built with a different engine version:
ConveyorPlugin
ConveyorSystemPlugin
Would you like to rebuild them now?
Hi!
The project you uploaded appears to have been built with an older version of the plugin, which is not called that. The blueprints in the project are corrupted.
